### ISSUE TITLE
Need a method to change the textAllCaps for the title.

### ISSUE THREAD

**Issue by chornomor** [faogustavo/MaterialTabs#3]
Our customer want to see tabs in lowercase and I did not find how I can change textAllCaps=true. 
Could you add a method for this, please?

**Comment by faogustavo** [comment]
@chornomor I'm not sure it is possible in the current version. 
But I can take some time to try to add this feature.

**Comment by faogustavo** [comment]
@chornomor Just added this at the [1.3.2 release](https://github.com/faogustavo/MaterialTabs/releases/tag/1.3.2).
Now you can disable the allCaps using the `tabLayout.setAllCaps(false);` method.

**Comment by chornomor** [comment]
Thank's, man:)
